# Generated by Django 4.0.6 on 2022-11-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='immagine',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cognome',
            new_name='surname',
        ),
    ]
