# Generated by Django 4.0.6 on 2022-12-17 13:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('liceo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('cognome', models.CharField(max_length=32, null=True)),
                ('nascita', models.DateField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=32, populate_from=('nome',), unique=True)),
                ('indirizzo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.indirizzo')),
            ],
            options={
                'verbose_name_plural': 'studenti',
            },
        ),
    ]
