# Generated by Django 4.0.6 on 2022-12-17 13:59

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studente',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=32, populate_from=('nome', 'cognome'), unique=True),
        ),
    ]
