# Generated by Django 3.2.16 on 2022-12-21 08:25

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_studente_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indirizzo',
            options={'verbose_name_plural': 'indirizzi'},
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=32, populate_from=('nome',), unique=True),
        ),
    ]
