# Generated by Django 3.2.16 on 2022-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
