# Generated by Django 3.2.16 on 2022-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
